name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: syllabus.tex
          latexmk_use_xelatex: true
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: syllabus.pdf
